### ISSUE TITLE
No “app ID” provided by Spotify

### ISSUE THREAD

**Issue by jnv** [tiagomendesdantas/Rspotify#1]
The `spotifyOAuth()` function requires three parameters: `app_id`, `client_id` and `client_secret`. 

I have registered a new application at https://developer.spotify.com/my-applications/ – however, only “Client ID” and “Client Secret” is provided for an application, nothing like “App ID” – even [authorization guide](https://developer.spotify.com/web-api/authorization-guide/) mentions only client secret and client ID. 

So my question is, what should be used for `app_id` parameter, if it is needed at all? Using application's name or `client_id` as `app_id` did not seem to do the job.

**Comment by jnv** [comment]
Okay, I think I had a mistake in my ID or secret and looking at documentation for `httr::oauth_app` I figured that `app_id` is for internal use only. Still the documentation is a bit misleading, instead of stating:

> In order to access many of the functions you need a authenticated token. You can get one accessing this link to create a Spotify app and get app_id, client_id and client_secret. (Don't forget to put http://localhost:1410/ in Redirect URIs) 

You could say for example:

In order to access the Spotify API you need to register an application. Create a new application at [Spotify Developer portal](https://developer.spotify.com/my-applications/), add `http://localhost:1410/` to _Redirect URIs_ and copy _Client ID_ and _Client Secret_.

Then you can use the client ID and secret with Rspotify like this:

```R
keys <- spotifyOAuth("My Rspotify Project", "client_id", "client_secret")
```

The first parameter is an internal identification for token if you wish to save authorization. Replace `"client_id"` and `"client_secret"` with information copied from Spotify Developer portal.

----

Also, perhaps `app_id` could be an optional parameter and you could provide a default value passed to `httr::oauth_app`.

**Comment by sillasgonzaga** [comment]
I haven't figured it out. I'm stil getting the **INVALID_CLIENT: Invalid redirect URI** error.

**Comment by tiagomendesdantas** [comment]
I decided to let the user put the name in order to better organize each app (in the case of having many apps). But you are absolutely right... It's a bit confusing. I'm gonna write a better explanation on that.
