### ISSUE TITLE
Error in getRelated with artist ID

### ISSUE THREAD

**Issue by gabrielvazdemelo** [tiagomendesdantas/Rspotify#4]
While using the function _getRelated_ with artist ID I get some error. It works fine with the name, but some related can be misunderstood because of repeated names. So, while using the artist ID I get that:

Error in req$artists$items[, c("id", "name", "popularity", "genres", "type")] : 
  incorrect number of dimensions

**Comment by tiagomendesdantas** [comment]
I'll be rewriting some functions in the next couple of days and hopefully this will be fixed. Thanks
