### ISSUE TITLE
getRelated

### ISSUE THREAD

**Issue by vincent-dube-bistodeau** [tiagomendesdantas/Rspotify#7]
Is there any change from the Spotify API?
I can't use getRelated anymore.

I'm getting "Error in open.connection(con, "rb") : HTTP error 401."
Any insight?

**Comment by tiagomendesdantas** [comment]
Yes! Apparently, now almost all endpoints need authentication. I'll be fixing it in the next couple of days, since this is affecting other functions. Thanks for letting me know.

**Comment by brunaw** [comment]
Hello! I'm getting: 
```
Error in httr::config(token = token) : 
  argumento "token" ausente, sem padrão
```
While trying to use getRelated.

**Comment by bbrewington** [comment]
I wrote some code in #11 that solves the issue for getAlbums.  Working through some of the other functions if nobody beats me to it!

**Comment by tiagomendesdantas** [comment]
Thanks a lot Bret and Bruna!
